#!/bin/bash

if [ 0 -ne "$(id -u)" ]; then
    if sudo --version >/dev/null 2>&1
    then
        sudoprefix=sudo
    else
        sudoprefix=
    fi
else
    sudoprefix=
fi

test_tools(){
    { docker --version > /dev/null 2>&1; } 
}

install_tools(){
    { apt --version >/dev/null 2>&1 && $sudoprefix apt install -y  docker ; } ||
    { yum --version >/dev/null 2>&1 && $sudoprefix yum install -y  docker ; } ||
    { zypper --version >/dev/null 2>&1 && $sudoprefix zypper --non-interactive  install docker ; } ||
    { pacman -V >/dev/null 2>&1 && $sudoprefix pacman -S --noconfirm --needed  docker ; } ||
    { pkg list-installed >/dev/null 2>&1 && $sudoprefix pkg install -y  docker ; } || # termux
    { pkg help >/dev/null 2>&1 && $sudoprefix pkg install -y  docker ; } 
}

exit_error(){
    echo $1
    exit -1
}

test_tools || install_tools && systemctl start docker 
test_tools || exit_error "tools install error"

docker run --rm -d --net=host --name=blog_server wmb521/blog_run_docker && echo -e "http://localhost:8080 for home page\nhttp://localhost:8080/admin for admin page\n"
